NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.stellar.org/federation"
TRANSFER_SERVER="https://api.stellar.org/auth"
SIGNING_KEY="GD57PYZVUO4P4IDGX7OX4RTLOKI2R5MHJUEZ4SAXAS3TY37QMMJX4BN7"
HORIZON_URL="https://horizon.stellar.org"
ACCOUNTS=["GD57PYZVUO4P4IDGX7OX4RTLOKI2R5MHJUEZ4SAXAS3TY37QMMJX4BN7","GASSQNUYTK3OQX23EMYD6DTU2YCKBSMRPZV4VC6TQHBM6TXIQPZDAT2D","GAE65F2YCYMM62F2AGOD4Q76JYMQOSDCRTBB3IQMJ3IE3MUTJQMYXKN6"]

VERSION="2.0.0"
[DOCUMENTATION]
ORG_NAME="Gr. SSLG Meteors"
ORG_URL="https://privateofcwest.pages.dev/"
ORG_LOGO=""
ORG_DESCRIPTION="Gr. SSLG Meteors. REITS, mREITS, CRE and Residential real estate."
ORG_PHYSICAL_ADDRESS="1901 Avenue of the Stars, Los Angeles, CA 90067, United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER="t.me/Private_OfcLABot"
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE="grsslg*keybase io"
ORG_TWITTER=""
ORG_GITHUB="https://privateofcwest.pages.dev/"
ORG_OFFICIAL_EMAIL=""

[[PRINCIPALS]]

name="Gr. SSLG Meteors, BT"
email=""
keybase=""
twitter=""
github=""
id_photo_hash=""
verification_photo_hash=""

[[CURRENCIES]]
code="GrSSLG"
issuer="GASSQNUYTK3OQX23EMYD6DTU2YCKBSMRPZV4VC6TQHBM6TXIQPZDAT2D"
name="Gr. SSLG Meteors"
desc="Fungible base/counter cryptocurrency"
conditions="Active burn policy. Issuer may mint additional tokens."
image=""
attestation_of_reserve="https://stellar.expert/explorer/public/asset/GrSSLG-GASSQNUYTK3OQX23EMYD6DTU2YCKBSMRPZV4VC6TQHBM6TXIQPZDAT2D-2?filter=markets"
fixed_number=false
max_number=1000000000
display_decimals=4
is_unlimited=true
is_asset_anchored=false

[[CURRENCIES]]
code="RENFT"
issuer="GCH543CFFBLHVZDC7GBQFQ2LCEY5EGDGHUOTKPASXEMB6ITE23VY64EH"
name="Real Estate NFT"
desc="Real Estate NFT deed acquisition."
image="https://litemint.infura-ipfs.io/ipfs/QmZsA5pcDAmP46pJeCYZ5TvmBgrzKgjErubZpnaaNzRnaw"
attestation_of_reserve="https://stellar.expert/explorer/public/asset/RENFT-GCH543CFFBLHVZDC7GBQFQ2LCEY5EGDGHUOTKPASXEMB6ITE23VY64EH-2"
fixed_number=false
max_number=1
display_decimals=7
is_unlimited=true
is_asset_anchored=true
anchor_asset_type="nft"
anchor_asset="Real Estate NFT Rights"

[[CURRENCIES]]
code="RENFT"
isuer="GCVN2UJLKNCTFZSTREODJZAXOUCFZHGYMQOA6MX5AL45NUPSFGI7PWQM"
name="Real Estate NFT"
desc="Real Estate NFT Rights. Proceeds go to RENFT issuer GCH54...64EH for deed acquisition. Every real estate NFT is issued a unique Identifier"
image="https://github.com/PrivateOfc/west/blob/main/images/Real%20Estate%20NFT%20Rights.png"
attestation_of_reserve="https://stellar.expert/explorer/public/asset/RENFT-GCVN2UJLKNCTFZSTREODJZAXOUCFZHGYMQOA6MX5AL45NUPSFGI7PWQM-2"
fixed_number=true
max_number=5000
display_decimals=7
is_unlimited=true
is_asset_anchored=true
anchor_asset_type="nft"
anchor_asset="Real Estate NFT Rights"
